from __future__ import annotations

import json
from pathlib import Path

from .schema import DaosPack


def render_assistant_charter(pack: DaosPack) -> str:
    charter = pack.assistant_charter
    header = "# Assistant Charter\n\n"
    if pack.generator == "scripts/daos_wizard.py":
        header += "> Generated by `scripts/daos_wizard.py`.\n> Review and refine after real use.\n\n"
    else:
        header += "> Starter-pack working copy.\n> Fill this first.\n> For the reusable source version, see `templates/assistant-charter-template.md`.\n\n"
    return header + (
        "## 1. Core outcome\n\n"
        f"- Primary outcome: {charter.primary_outcome}\n"
        f"- The main kind of help this assistant should provide: {charter.main_help}\n\n"
        "## 2. Main failure mode\n\n"
        f"- Primary failure mode: {charter.primary_failure_mode}\n"
        f"- What would make the assistant feel unhelpful, unsafe, noisy, or trust-reducing fastest: {charter.unhelpful_fastest}\n\n"
        "## 3. Uncertainty behavior\n\n"
        f"- Default uncertainty behavior: {charter.default_uncertainty_behavior}\n"
        f"- Ask-first trigger: {charter.ask_first_trigger}\n"
        f"- Act-with-defaults trigger: {charter.act_with_defaults_trigger}\n\n"
        "## 4. Proactive behavior\n\n"
        f"- Proactive by default or mostly reactive: {charter.proactive_mode}\n"
        f"- What should trigger interruption: {charter.interruption_trigger}\n"
        f"- What should usually be batched or left quiet: {charter.batch_quiet}\n\n"
        "## 5. Safety / approval boundary\n\n"
        f"- Low-stakes reversible actions that can proceed: {charter.low_stakes_actions}\n"
        f"- Actions that always require approval: {charter.always_require_approval}\n"
        f"- Any special red lines: {charter.special_red_lines}\n\n"
        "## 6. Desired feel\n\n"
        f"- Desired feel in daily use: {charter.desired_feel}\n"
        f"- Tone to avoid: {charter.tone_to_avoid}\n"
        f"- Comparison or metaphor if helpful: {charter.comparison}\n"
    )


def render_operating_profile(pack: DaosPack) -> str:
    profile = pack.operating_profile
    lane_lines = "\n".join(f"- {lane}" for lane in profile.top_level_lanes)
    lane_blocks = "\n\n".join(
        (
            f"### Lane: {lane.name}\n"
            f"- Status: {lane.status}\n"
            f"- Foreground: {lane.foreground}\n"
            f"- Pressure: {lane.pressure}\n"
            f"- Short note: {lane.short_note}"
        )
        for lane in profile.lane_snapshots
    )
    header = "# Operating Profile\n\n"
    if pack.generator == "scripts/daos_wizard.py":
        header += "> Generated by `scripts/daos_wizard.py`.\n> Review and refine after real use.\n\n"
    else:
        header += "> Starter-pack working copy.\n> Fill this after the assistant charter.\n> For the reusable source version, see `templates/operating-profile-template.md`.\n\n"
    return header + (
        "## 1. Assistant charter\n\n"
        f"- Primary outcome: {profile.primary_outcome}\n"
        f"- Primary failure mode: {profile.primary_failure_mode}\n"
        f"- Uncertainty behavior: {profile.uncertainty_behavior}\n"
        f"- Proactive behavior: {profile.proactive_behavior}\n"
        f"- Safety / approval boundary: {profile.safety_approval_boundary}\n"
        f"- Desired feel: {profile.desired_feel}\n\n"
        "## 2. Top-level lane map\n\n"
        f"{lane_lines}\n\n"
        "## 3. Per-lane snapshot\n\n"
        f"{lane_blocks}\n\n"
        "## 4. Reminder / planning defaults\n\n"
        f"- Master list source: {profile.master_list_source}\n"
        f"- Review layer / dashboard: {profile.review_layer_dashboard}\n"
        f"- Same-day overdue follow-up: {profile.same_day_overdue_follow_up}\n"
        f"- Focus-set default: {profile.focus_set_default}\n"
        f"- Importance / urgency rules: {profile.importance_urgency_rules}\n\n"
        "## 5. Memory / trust defaults\n\n"
        f"- Memory front door: {profile.memory_front_door}\n"
        f"- Durable memory home: {profile.durable_memory_home}\n"
        f"- Verified reality rule: {profile.verified_reality_rule}\n"
        f"- Ask-vs-act rule: {profile.ask_vs_act_rule}\n"
        f"- Escalation / approval rule: {profile.escalation_approval_rule}\n"
        f"- Durable capture rule: {profile.durable_capture_rule}\n\n"
        "## 6. Calibration later\n\n"
        f"- What feels too heavy? {profile.calibration_too_heavy}\n"
        f"- What still gets missed? {profile.calibration_still_missed}\n"
        f"- Which lane needs more support? {profile.calibration_lane_support}\n"
        f"- What should be added, removed, or softened? {profile.calibration_add_remove_soften}\n"
    )


def render_pack_manifest(pack: DaosPack) -> str:
    return json.dumps(pack.manifest_dict(), indent=2) + "\n"


def write_pack_core_files(destination: Path, pack: DaosPack, *, overwrite: bool = True) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    core_files = {
        "assistant-charter.md": render_assistant_charter(pack),
        "operating-profile.md": render_operating_profile(pack),
        "daos-pack.json": render_pack_manifest(pack),
    }
    for name, content in core_files.items():
        target = destination / name
        if target.exists() and not overwrite:
            continue
        target.write_text(content, encoding="utf-8")
