#!/usr/bin/env python3
"""Interactive DAOS setup wizard that generates a filled starter pack."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from daos_bootstrap import bootstrap


MEMORY_FRONT_DOOR = "local thread first, then hot cache, then agent continuity"
DURABLE_MEMORY_HOME = "wiki first, with repo/docs used for publishable framework outputs"
VERIFIED_REALITY_RULE = "live files, runtime, and current state outrank remembered context for operational facts"
ASK_VS_ACT_RULE = "ask when ambiguity changes the action; act when intent is clear and stakes are low or reversible"
DURABLE_CAPTURE_RULE = (
    "if a second review shows something should not live mainly in hot cache or chat, "
    "create/update a durable note in the same pass"
)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run a compact DAOS setup wizard and generate a filled starter pack."
    )
    parser.add_argument("output_dir", help="Destination directory for the generated DAOS pack")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace an existing non-empty destination directory",
    )
    return parser.parse_args(argv)


def prompt(question: str) -> str:
    try:
        answer = input(f"{question}\n> ").strip()
    except EOFError as exc:
        raise ValueError("Wizard input ended early.") from exc
    if not answer:
        raise ValueError(f"A response is required for: {question}")
    return answer


def parse_csv_list(raw: str) -> list[str]:
    items = [item.strip() for item in raw.split(",") if item.strip()]
    if not items:
        raise ValueError("Please provide at least one item.")
    return items


def parse_yes_no(raw: str) -> bool:
    value = raw.strip().lower()
    if value in {"y", "yes"}:
        return True
    if value in {"n", "no"}:
        return False
    raise ValueError("Please answer yes or no.")


def lane_note(lane: str, foreground_lanes: set[str], slips: str) -> str:
    if lane in foreground_lanes:
        return f"currently foreground; first-pass support should reduce drift around {slips.lower()}"
    return "active but not currently foreground; refine later if this lane needs more structure"


def fill_assistant_charter(destination: Path, answers: dict[str, object]) -> None:
    content = f"""# Assistant Charter

> Generated by `scripts/daos_wizard.py`.
> Review and refine after real use.

## 1. Core outcome

- Primary outcome: {answers['outcome']}
- The main kind of help this assistant should provide: practical chief-of-staff support oriented around continuity, prioritization, and follow-through

## 2. Main failure mode

- Primary failure mode: {answers['failure_mode']}
- What would make the assistant feel unhelpful, unsafe, noisy, or trust-reducing fastest: {answers['failure_mode']}

## 3. Uncertainty behavior

- Default uncertainty behavior: {answers['uncertainty_behavior']}
- Ask-first trigger: ambiguity that would change the action or cross an approval boundary
- Act-with-defaults trigger: low-stakes reversible drafting, organization, or setup work where likely intent is clear

## 4. Proactive behavior

- Proactive by default or mostly reactive: proactive with compression
- What should trigger interruption: {answers['proactive_behavior']}
- What should usually be batched or left quiet: low-value noise, speculative ideas, and repetitive confirmations

## 5. Safety / approval boundary

- Low-stakes reversible actions that can proceed: drafting, summarizing, organizing, and lightweight investigation when intent is clear
- Actions that always require approval: {answers['approval_boundary']}
- Any special red lines: never present remembered context as live truth when files, runtime, or current state can be checked

## 6. Desired feel

- Desired feel in daily use: {answers['desired_feel']}
- Tone to avoid: overexplaining, broad nagging, or fake certainty
- Comparison or metaphor if helpful: a practical operator rather than a chatbot concierge
"""
    (destination / "assistant-charter.md").write_text(content, encoding="utf-8")


def fill_operating_profile(destination: Path, answers: dict[str, object]) -> None:
    lanes: list[str] = answers["lanes"]  # type: ignore[assignment]
    foreground_lanes = set(answers["foreground_lanes"])  # type: ignore[arg-type]
    importance_over_urgency = "importance outranks urgency when they conflict" if answers["importance_over_urgency"] else "urgency outranks importance when they conflict"

    lane_blocks = []
    for lane in lanes:
        foreground = "yes" if lane in foreground_lanes else "no"
        pressure = "high" if lane in foreground_lanes else "medium"
        lane_blocks.append(
            f"### Lane: {lane}\n"
            f"- Status: active\n"
            f"- Foreground: {foreground}\n"
            f"- Pressure: {pressure}\n"
            f"- Short note: {lane_note(lane, foreground_lanes, answers['slips'])}\n"
        )

    lane_section = "\n".join(lane_blocks)
    content = f"""# Operating Profile

> Generated by `scripts/daos_wizard.py`.
> Review and refine after real use.

## 1. Assistant charter

- Primary outcome: {answers['outcome']}
- Primary failure mode: {answers['failure_mode']}
- Uncertainty behavior: {answers['uncertainty_behavior']}
- Proactive behavior: {answers['proactive_behavior']}
- Safety / approval boundary: {answers['approval_boundary']}
- Desired feel: {answers['desired_feel']}

## 2. Top-level lane map

""" + "\n".join(f"- {lane}" for lane in lanes) + f"""

## 3. Per-lane snapshot

{lane_section}
## 4. Reminder / planning defaults

- Master list source: {answers['master_list_source']}
- Review layer / dashboard: one clean review layer or dashboard if useful
- Same-day overdue follow-up: yes, but gentle
- Focus-set default: 3 active priorities
- Importance / urgency rules: {importance_over_urgency}

## 5. Memory / trust defaults

- Memory front door: {MEMORY_FRONT_DOOR}
- Durable memory home: {DURABLE_MEMORY_HOME}
- Verified reality rule: {VERIFIED_REALITY_RULE}
- Ask-vs-act rule: {ASK_VS_ACT_RULE}
- Escalation / approval rule: {answers['approval_boundary']}
- Durable capture rule: {DURABLE_CAPTURE_RULE}

## 6. Calibration later

- What feels too heavy? anything that becomes noisier than helpful in real use
- What still gets missed? {answers['slips']}
- Which lane needs more support? start by reviewing the foreground lanes first
- What should be added, removed, or softened? make one small correction at a time after the first week of use
"""
    (destination / "operating-profile.md").write_text(content, encoding="utf-8")


def collect_answers() -> dict[str, object]:
    outcome = prompt("1. What should this assistant help with most?")
    failure_mode = prompt("2. What would make it feel unhelpful fastest?")
    uncertainty_behavior = prompt("3. When uncertain, how should it behave?")
    proactive_behavior = prompt("4. What should trigger interruption or proactive nudges?")
    approval_boundary = prompt("5. What always requires approval?")
    desired_feel = prompt("6. What should the assistant feel like in daily use?")
    lanes = parse_csv_list(prompt("7. What are the top active lanes right now? (comma-separated)"))
    foreground_lanes = parse_csv_list(prompt("8. Which lanes are in the foreground right now? (comma-separated)"))
    slips = prompt("9. What most often slips or gets dropped?")
    master_list_source = prompt("10. Where should the master task list live?")
    importance_over_urgency = parse_yes_no(prompt("11. Should importance outrank urgency? (yes/no)"))

    return {
        "outcome": outcome,
        "failure_mode": failure_mode,
        "uncertainty_behavior": uncertainty_behavior,
        "proactive_behavior": proactive_behavior,
        "approval_boundary": approval_boundary,
        "desired_feel": desired_feel,
        "lanes": lanes,
        "foreground_lanes": foreground_lanes,
        "slips": slips,
        "master_list_source": master_list_source,
        "importance_over_urgency": importance_over_urgency,
    }


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    print("DAOS interactive setup wizard")
    print("This is a short first-pass install, not a full life-modeling session.")

    try:
        answers = collect_answers()
        destination = bootstrap(args.output_dir, use_filled_example=False, force=args.force)
        fill_assistant_charter(destination, answers)
        fill_operating_profile(destination, answers)
    except (ValueError, OSError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"\nGenerated DAOS starter pack: {destination}")
    print("Next steps:")
    print("- review assistant-charter.md and operating-profile.md")
    print("- leave cadence-review.md for later")
    print("- run python scripts/daos_validate.py <pack-dir> to check readiness")
    print("- use harness/first-week.md after the first install")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
